leanspace/terraform-provider-leanspace

- .github/workflows/release.yml
- README.md
- scripts/version-incrementer.sh
- In this PR, I've added release version validation for terraform releases.
- This PR now makes it possible to deploy terraform release with an automated workflow without the need of tagging commits. You simply need to specify the version you wish to release and the type of release whether major, minor or patch.
- Everytime the workflow is executed, 2 jobs will be run by it:
`version-validation`:
- This job validates the provided release version and checks if it complies with the format.
- It also checks if it matches the release type provided. For example, the last release version was `v0.8.4` and you are now releasing a new patch, it will check if the new patch version is `v0.8.5`.
- The script `version-incrementer.sh` is used for generating the next incremental version. …
> SDEVOPS-358 - Improving terraform release workflow

- .github/workflows/release.yml
- Added the `needs` condition to `release-deployer` job to make sure it only gets triggered if `version-validation` job succeeds.
> SDEVOPS-358 - Added dependency condition for release-deployer job

- .github/workflows/release.yml
- Changes made in this PR will ensure that before new versions of terraform repository are released to the customers, either @jerome-leanspace or @elodietinland would have to approve the release to allow it to be deployed.
> SDEVOPS-365 - Added approval step to terraform release

- services/teams/access_policies/schemas.go
Fixes for Access policies:
- Statements is actually optional
- `*:*` is allowed
> BUZZ-305: allow empty statements and *:* in access policy

- README.md
- provider/client.go
- provider/provider.go
Right now a custom host can be set but with this way we can just use the environment to deduce the api address, the host still takes priority and can be used to test locally
Region was not supported, this adds the possibility to specify the region --> an alternative would be to deduce it from the tenants api: https://api.leanspace.io/tenants-repository/swagger-ui/index.html?configUrl=/tenants-repository/v3/api-docs/swagger-config#/tenants-controller/getByTenantKey --> What do you think?
Depending on Pritesh's finding this PR may change
> BUZZ-370: support custom environment + region

- services/teams/access_policies/parsers.go
- services/teams/access_policies/schemas.go
It seems actions of an Access Policies are automatically reorderd by the API
This fixes the issue were terraform detects a change because we don't have the same order
Edit: cc @kbudkaLeanspace Can you confirm that this is an expected behaviour? --> It is confirmed that the API reorders actions alphabetically but also the statements per name
> BUZZ-000: fix access policy's action's order

- .github/workflows/release.yml
This is to avoid such "issue": https://github.com/leanspace/terraform-provider-leanspace/actions/runs/6504976466/job/17667778091
I haven't tested it but from the docs it says it kills it so I suspect the following tasks will not be done, right?
> BUZZ-000: add a timeout

- services/commands/command_definitions/schemas.go
This fixes a pending issue where the identifier was considered as required instead of optional
Another change (bigger) will come later to support the issue of Quantum (changing the argument/metadata is not working)
> BUZZ-428: command's definition's identifier should be optional

- provider/client.go
Mainly for plugins/processors, the timeout can be short.
We imagine the customer has fiber optics, with this someone can upload 10 (default parallelism for our terraform provider) processors or plugins with the maximum size (250 MB) with a 66Mb/s (previously 166Mb/s) connection.
For a file at a time it requires a 6,6 Mb/s (16Mb/s previously) connection which should be available to most customers.
There's a possibility to create a resource without a timeout but it requires some change in the code, which I don't believe is necessary
Let me know if you think of another value for the timeout.
> BUZZ-447: increase timeout

- helper/validation.go
- services/orbits/orbits/schemas.go
- testing/orbits/orbits/main.tf
see also https://github.com/leanspace/integration-testing/pull/463 & https://github.com/leanspace/orbits-repository/pull/89
> BLUE-1648 update ideal orbit schemas with respect to newly introduced constraints

- services/routes/routes/parsers.go
- services/routes/routes/schemas.go
Changing from List to Set so it doesn't check the order anymore
> GOLDS-666: don't check order for processors in routes

- services/streams/streams/schemas.go
Increased maximum depth from 5 to 11. 11 is required for Sateliot Demo.
We should think of a better long term solution but the higher the depth, the longer it may take for terraform to process a stream resource.
> BUZZ-446: increase stream maximum depth

- provider/client.go
When using terraform with a high number of resources (either creation, update or even deletion), the token is only valid for 1 hour. When the token expires it still tries to do the remaining operations which can still take some time. You see that some/most of the resources were not created but only after every API calls are made.
This PR automatically refreshes the token before the expiration of the token.
> BUZZ-000: refresh token before it expires

- provider/client.go
- testing/records/record_templates/main.tf
With this change terraform will use the new endpoint to retrieve the token
> BUZZ-731: use new endpoint to get token

- services/asset/nodes/parsers.go
- services/asset/nodes/requests.go
- services/asset/nodes/validation.go
Fix:
- Norad ID and International Designator properties were always created even when no data were given
- Updating Built-in properties were not working
- Verify that correct built-in properties are passed (elevation, latitude, longitude for Ground Stations and International Designator, Norad ID and TLE for Satellite). If the user wish to create properties with the same name it shall be done using the`leanspace_properties` resources
> RED-393: fix built-in properties for topology

- .gitignore
- .terraform-registry
Temporary addition so we can change the owner of the provider ([see](https://desk.zoho.eu/agent/lnssupport/leanspace/tickets/details/121641000005039001))
> BUZZ-000: change owner

- services/monitors/action_templates/main.go
- services/monitors/action_templates/schemas.go
- services/monitors/monitors/models.go
- services/monitors/monitors/parsers.go
- services/monitors/monitors/requests.go
- services/monitors/monitors/schemas.go
Breaking change:
- renamed `action_template_ids` to `action_template_links`
Feat:
- `action_template_links` contains the id of the action template + `triggeredOn` optionally
- Some duplication due to Go not having inheritance
> BUZZ-639: allow triggerOn on action template's linking

- .terraform-registry
- services/plugins/plugins/parsers.go
- services/streams/streams/main.go
- services/streams/streams/requests.go
Feat:
- Implement async creation of stream (will be slower for small streams ~ 2s extra for the extra calls)
- I had to reimplement the normal Get for Stream (maybe @N1ark has an idea on how to use the generic implementation)
- I've not implemented a timeout (see the second commit that removes it)
Fix:
- In Plugins the Failed State was not throwing an error
- Removed the temporary terraform-registry file
> BUZZ-774: implement async stream creation

- services/resources/resources/schemas.go
There seem to be no limit on the backend so this removes the limitation on terraform
> BUZZ-000: remove resource's value limit

- examples/resources/leanspace_streams.tf
- services/streams/streams/schemas.go
- services/streams/streams/validation.go
- testing/streams/streams/main.tf
Fix:
- Allow 64 bits integer and unsigned integer since it's now allowed in the API
- Use the "new" format (nested JSON object) everywhere to be consistent
> BUZZ-000: allow 64 bits integer in Stream

- provider/provider.go
When running terraform on Github action I noticed the following crash. This was caused by a mistake of mine which lead to a variable being empty (empty string).
Empty values were allowed in Terraform for the credentials. This PR removes this possibility and provides a corresponding error message.
```
Planning failed. Terraform encountered an error while generating this plan.
╷
│ Error: Request cancelled
│ 
│   with provider["registry.terraform.io/leanspace/leanspace"],
│   on main.tf line 9, in provider "leanspace":
│    9: provider "leanspace" {
│ 
│ The plugin.(*GRPCProvider).ConfigureProvider request was cancelled.
╵
Stack trace from the terraform-provider-leanspace_v8.2.1 plugin:
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation …
```
> BUZZ-000: fail fast when no credentials are supplied

- provider/client.go
- services/requests/feasibility_constraint_definitions/parsers.go
- services/requests/request_definitions/parsers.go
There is a small risk that the renewal of the token fails (network issue, problem on teams, ...). If this happens we did nothing, this could lead to using an expired token and thus having responses with the 401 http code.
To avoid this,  if an error happens it will try to request again the token after 5 seconds (rather than the current 58 minutes) and if there is 6 consecutive errors then a panic is sent and the terraform process with end with the message: ` Error: Request cancelled` (I couldn't modify the message).
Also I removed some unused code and logging.
> BUZZ-000: avoid token expiration

- examples/resources/leanspace_feasibility_constraint_definitions.tf
- examples/resources/leanspace_streams.tf
- services/requests/feasibility_constraint_definitions/schemas.go
- services/requests/request_definitions/schemas.go
- testing/requests/feasibility_constraint_definitions/main.tf
- testing/streams/streams/main.tf
[prerequisite](https://github.com/leanspace/requests-repository/pull/87)
> BLUE-2636: allow TIMESTAMP attributes on requests

- helper/general_objects/parsers.go
The field `required` was never correctly mapped when present in the constraint of an array argument
> BUZZ-000: correctly map required in element constraint
